export type ModelCategory = "codigo" | "razonamiento" | "imagen";

export interface CatalogModel {
  id: string;
  name: string;
  modelId: string;
  category: ModelCategory;
}

export interface Settings {
  nimKey: string;
  model: string;
  proxy: string;
  systemPrompt: string;
  temperature: number;
  maxTokens: number | null;
  ghToken: string;
  bridgeUrl: string;
  bridgeToken: string;
}

export interface ToolCallFunction {
  name: string;
  arguments: string;
}

export interface ToolCall {
  id: string;
  type: "function";
  function: ToolCallFunction;
}

/** OpenAI-style multi-part message content, used for vision attachments. */
export type MessageContentPart =
  | { type: "text"; text: string }
  | { type: "image_url"; image_url: { url: string } };

export type MessageRole = "system" | "user" | "assistant" | "tool";

export interface ChatMessage {
  role: MessageRole;
  content: string | MessageContentPart[];
  /** Only present on assistant messages that requested tool calls. */
  tool_calls?: ToolCall[];
  /** Only present on role:"tool" messages, echoes the originating tool_call id. */
  tool_call_id?: string;
  /** Non-standard field: base64 PNG for an assistant message generated by an "imagen" model. */
  image?: string;
}

export interface Conversation {
  id: string;
  title: string;
  messages: ChatMessage[];
  updatedAt: number;
}

export interface ConversationExport {
  app: "vokchat";
  version: 1;
  exportedAt: number;
  conversations: Conversation[];
}

export interface ToolDef {
  type: "function";
  function: {
    name: string;
    description: string;
    parameters: {
      type: "object";
      properties: Record<string, unknown>;
      required: string[];
    };
  };
}

export interface RunToolResult {
  [key: string]: unknown;
}
